*py np arr conctination and split

In [2]:
import numpy as np

In [3]:
arr1=np.arange(1,17).reshape(4,4)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [4]:
arr2=np.arange(17,33).reshape(4,4)
print(arr2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [5]:
np.concatenate((arr1,arr2))          # for concatenate two or more matrix arrayy coloumn wise

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [6]:
np.concatenate((arr1,arr2),axis=1)          # for concatenate two or more matrix arrayy row wise in same colm

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [7]:
np.vstack((arr1,arr2))     # for concatenate two or more matrix arrayy coloumn wise(verticle wise)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [8]:
np.hstack((arr1,arr2))     # for concatenate two or more matrix arrayy row wise(horizental wise)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [9]:
np.split(arr1,2)             #for break or splite of elem of an array matrix

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [10]:
list1=np.split(arr1,2)  #for check ele list form of other formate(type)

In [11]:
type(list1)     #type of list 1

list

In [12]:
list1[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
type(list1[0])         #type of list1 array

numpy.ndarray

In [14]:
np.split(arr1,2,axis=1)      #for split/break of elem of an arr mat in row wise

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [15]:
d1=np.array([4,7,1,3,9])

In [16]:
np.split(d1,[1,3])

[array([4]), array([7, 1]), array([3, 9])]